TILE_SPRITE_SCALING = 1
PLAYER_SCALING = 1

SCREEN_WIDTH = 2430
SCREEN_HEIGHT = 1620
SCREEN_TITLE = "Risk Of Pog"
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SPRITE_SCALING)
SCALING = 1

# Physics
JUMP_SPEED = 25
GRAVITY = 1.5
MAX_SPEED = 100
ACCELERATION_RATE = 0.5
HORIZONTAL_DAMPING = 0.15
HORIZONTAL_DAMPING_STOPPING = 0.4
CUT_JUMP_HEIGHT = 0.5
FRICTION = 0.0

BULLET_SPEED = 50

UPDATES_PER_FRAME = 5
MOVEMENT_SPEED = 7

SPRITE_SCALING_LASER = 1

ZOOM_AMMOUNT = 400
